# Trascrizione del menù PDF (prezzi in euro)
MENU = [
 ("antipasti", "Antipasti", [
   ("Mare", [
     ("Misto pesce crudo","","23,00"),("Antipasto Maremonti","","16,00"),("Alici marinate","","10,00"),
     ("Antipasto di mare caldo","","13,00"),("Capesante gratinate 3 pz.","","10,00"),
     ("Carpaccio di spada al limone","","10,00"),("Cocktail di gamberi","","10,00"),("Crostini al salmone","","10,00"),
     ("Gamberetti/Piovra alla Catalana","","12,00"),("Impepata di cozze","","10,00"),("Misto marinato","","13,00"),
     ("Piovra con patate","","13,00"),("Sautè di gamberi con carciofi freschi e trevisana","","12,00"),
     ("Tentacolo di polipo con rucola e pomodorini","","14,00")]),
   ("Terra", [
     ("Affettato misto con grana","","10,00"),("Gnocco fritto con prosciutto crudo","","10,00"),
     ("Bresaola carciofi grana","","10,00"),("Bruschette","","4,00"),("Crostini di funghi porcini trifolati","","10,00"),
     ("Misto di bruschette","","8,00"),("Crudo e bufala","","10,00")]),
 ]),
 ("primi", "Primi", [
   ("Mare", [
     ("Spaghetti alle vongole e astice tagliato","","20,00"),("Tagliatelle maremonti","","12,00"),
     ("Spaghetti sottocoperta","","14,00"),("Spaghetti alle vongole veraci","","14,00"),
     ("Spaghetti alle vongole veraci e bottarga","","16,00"),("Linguine con gamberone e scampone","","17,00"),
     ("Linguine all'astice","","20,00"),("Pappardelle gamberetti e zucchine","","11,00"),
     ("Tagliatelle capesante e fiori di zucca","","12,00"),("Tagliatelle al salmone","","11,00"),
     ("Risotto con scampetti e fiori di zucca","","13,00"),("Risotto ai frutti di mare","","14,00"),
     ("Risotto gamberetti e rucola","","10,00"),("Spaghetti al nero di seppia","","13,00"),
     ("Penne con scampi e zucchine","","12,00")]),
   ("Terra", [
     ("Spaghetti alla carbonara","","10,00"),("Pappardelle ai funghi porcini","","10,00"),
     ("Penne della casa","porcini e ragù di manzo","10,00"),("Penne Sancho Panza","","10,00"),
     ("Penne alla tirolese","","10,00"),("Risotto taleggio e pistacchio","","11,00"),
     ("Risotto trevisana e scamorza","","10,00"),("Risotto ai funghi porcini","","10,00"),
     ("Risotto con spinaci e stracchino","","10,00"),("Gnocchi ai 4 formaggi","","10,00"),
     ("Gnocchi alla sorrentina","","10,00"),("Gnocchi gorgonzola e pistacchio","","10,00"),
     ("Gnocchi spinaci e zola","","10,00"),("Tortellini speck e trevisana","","10,00"),
     ("Fusilli alla diavola con ragù e mozzarella","","11,00")]),
 ]),
 ("secondi", "Secondi", [
   ("Mare", [
     ("Orata o branzino maremonti","","20,00"),("Astice alla catalana","","18,00"),
     ("Branzino o orata al forno con patate e carciofi","","17,00"),("Branzino o orata al sale","","15,00"),
     ("Branzino o orata alla griglia","","15,00"),("Filetto di branzino al cartoccio","","18,00"),
     ("Filetto di branzino alla crema di limone o al vino bianco","","15,00"),
     ("Filetto di branzino ai funghi porcini","","17,00"),("Fritto misto","","15,00"),
     ("Misto di pesce alla griglia o gratinata","","18,00"),("Pesce spada alla griglia","","13,00"),
     ("Pesce spada alla siciliana","","15,00"),("Spiedini di gamberoni con verdure alla griglia","","17,00"),
     ("Tagliata di branzino con patate o rucola","","15,00"),("Filetto di orata alla mediterranea","","14,00"),
     ("Tartar di salmone fresco","","14,00"),("Tagliata di salmone al pepe rosa","","14,00"),
     ("Zuppa di pesce","","20,00")]),
   ("Terra", [
     ("Costata all'antica","","18,00"),("Costata alla griglia","","17,00"),("Cotoletta alla milanese","","15,00"),
     ("Entrecôte con patate","","17,00"),("Filetto al cartoccio","","18,00"),("Filetto al pepe verde","","17,00"),
     ("Filetto alla griglia","","16,50"),("Filetto con aceto balsamico","","17,00"),("Filetto tartara","","17,00"),
     ("Filetto di manzo trifolato con funghi e riso bianco","","18,00"),
     ("Filetto di manzo alla crema di tartufo","","17,00"),("Grigliata mista di carne","","18,00"),
     ("Tagliata di costata all'olio e rosmarino","","18,00"),("Tagliata di manzo con porcini","","17,00"),
     ("Tagliata di manzo con rucola e grana","","16,00"),("Tagliata di manzo con trevisana e scamorza","","16,00")]),
 ]),
 ("pizze", "Pizze", [
   ("Classiche", [
     ("Marinara","pomodoro, olio, aglio, origano","4,50"),("Margherita","pomodoro, mozzarella, basilico","5,50"),
     ("Americana","pomodoro, mozzarella, wurstel, patatine","7,50"),
     ("Bufalina","pomodoro, mozzarella di bufala, basilico","7,50"),
     ("Calabrese","pomodoro, mozzarella, 'nduja, cipolle","7,00"),
     ("Capricciosa","pomodoro, mozzarella, cotto, funghi, carciofi, olive, capperi, acciughe, origano","7,50"),
     ("Crudo e rucola","pomodoro, mozzarella, prosciutto crudo, rucola","8,00"),
     ("Diavola","pomodoro, mozzarella, salame piccante","6,50"),
     ("Frutti di mare","pomodoro, misto frutti di mare (con mozzarella 10,50 €)","9,50"),
     ("Napoletana","pomodoro, mozzarella, acciughe, origano","6,50"),
     ("Ortolana","pomodoro, mozzarella, misto verdure alla griglia","7,50"),
     ("Prosciutto","pomodoro, mozzarella, prosciutto cotto","6,50"),
     ("Pugliese","pomodoro, mozzarella, cipolle, origano","6,50"),
     ("Quattro formaggi","mozzarella, scamorza, zola, brie, grana","7,50"),
     ("Quattro stagioni","pomodoro, mozzarella, funghi, carciofi, cotto, olive","7,00"),
     ("Regina","pomodoro, mozzarella, cotto, funghi","7,00"),
     ("Romana","pomodoro, mozzarella, acciughe, olive, capperi, origano","7,00"),
     ("Siciliana","pomodoro, acciughe, capperi, olive, origano","6,50"),
     ("Speck e zola","pomodoro, mozzarella, speck, zola","7,50"),
     ("Tonnara","pomodoro, mozzarella, tonno, cipolla","7,50")]),
   ("Speciali", [
     ("Maremonti","pomodoro, mozzarella, gamberetti, porcini","8,00"),
     ("Brie","pomodoro, mozzarella, brie, radicchio","7,00"),
     ("Davide","pomodoro, mozzarella, stracchino, rucola, bresaola","7,00"),
     ("Deliziosa","pomodoro, mozzarella, salame piccante, porcini","7,50"),
     ("Amatriciana","pomodoro, mozzarella, pancetta, cipolla, peperoncino","7,50"),
     ("Giancarlo","pomodoro, mozzarella, salame piccante, zola","7,50"),
     ("Giorgio","pomodoro, mozzarella, zucchine, salame piccante","7,00"),
     ("Quattro salumi","pomodoro, mozzarella, prosciutto, wurstel, salame piccante, salsiccia","7,50"),
     ("Sandi","pomodoro, mozzarella, zola, cipolla, speck","7,50"),
     ("Saporita","pomodoro, mozzarella, prosciutto, zola, peperoni","7,50"),
     ("Sfiziosa","pomodoro, mozzarella, salsiccia, scamorza","7,00"),
     ("Valtellina","pomodoro, mozzarella, bresaola, rucola, grana","7,50"),
     ("Venturina","pomodoro, mozzarella, cotto, porcini, scaglie di grana","8,00")]),
   ("Bianche e focacce", [
     ("Fumè","mozzarella, scamorza, radicchio, speck","7,00"),
     ("Andromeda","mozzarella di bufala, pomodoro fresco, basilico","7,50"),
     ("Bolognese","burrata, mortadella, granella di pistacchi","9,00"),
     ("Contadina","mozzarella, salsiccia, friarielli","7,00"),
     ("Alessia (focaccia)","crudo, rucola, pomodoro fresco, scaglie di grana","7,00"),
     ("Primavera (focaccia)","mozzarella di bufala, rucola, pomodoro fresco","7,00")]),
   ("Calzoni", [
     ("Calabrese","pomodoro, mozzarella, salame piccante","8,00"),
     ("Classico","pomodoro, mozzarella, prosciutto cotto","7,50"),
     ("Quattro formaggi","mozzarella, formaggi misti","7,50"),
     ("Farcito","pomodoro, mozzarella, cotto, funghi, carciofi","7,50"),
     ("Vegetariano","pomodoro, mozzarella, misto verdure alla griglia","7,50")]),
   ("Fantasia", [
     ("Del pizzaiolo","metà calzone, metà pizza","8,00"),
     ("Sfilatino di Capri","mozzarella, pomodoro fresco, cotto, ricotta, basilico","7,50")]),
 ]),
 ("piatti", "Insalatone e contorni", [
   ("Insalatone", [
     ("Maremonti","insalata verde, gamberetti, funghi porcini","12,00"),
     ("Zia Teresa","insalata verde, straccetti di pollo, mais, pomodorini e salsa rosa","11,00"),
     ("Classica","insalata verde, grana, rucola, gamberetti","11,00"),
     ("La Fattoria","insalata verde, bocconcini di mozzarella, rucola, carote grattugiate","9,00"),
     ("Mar Rosso","insalata verde, rucola, piovra, gamberetti, scaglie di grana","13,00"),
     ("Primavera","insalata verde, rossa, olive, pomodoro, tonno, uovo sodo","10,00")]),
   ("Cous cous", [("Cous cous di verdura","","10,00"),("Cous cous di pesce","","15,00")]),
   ("Contorni", [
     ("Insalata mista","","5,00"),("Patate fritte","","4,50"),("Patate prezzemolate","","4,50"),
     ("Sautè di patate","","4,50"),("Spinaci aglio e olio","","4,00"),("Spinaci al burro","","4,00"),
     ("Trevisana saltata","","4,00"),("Verdure alla griglia","","5,50"),("Verdure lesse","","4,50")]),
   ("Formaggi", [("Brie","","5,00"),("Gorgonzola","","5,00"),("Grana","","5,00"),("Taleggio","","5,00"),("Misto","","8,00")]),
 ]),
 ("dolci", "Dolci e caffè", [
   ("Dolci", [
     ("Dolci fatti in casa","","5,00"),("Affogato al caffè","","6,00"),("Affogato al liquore","","7,00"),
     ("Ananas o frutta di stagione","","4,50"),("Tartufo bianco o nero","","4,50"),("Torroncino semifreddo","","4,50"),
     ("Flute sorbetto al limoncello","","4,50"),("Coppa gelato","","4,50")]),
   ("Caffè", [("Caffè","","1,50"),("Corretto","","2,00"),("Cappuccino","","2,00"),("Ginseng","","2,00"),
              ("Decaffeinato","","2,00"),("Orzo","","2,00")]),
   ("Digestivo", [("Liquori","","4,00")]),
 ]),
 ("bevande", "Bevande e vini", [
   ("Bibite", [("Acqua 3/4 lt","","2,50"),("Coca, Fanta, Sprite","","2,50"),("Thè alla pesca o al limone","","2,00")]),
   ("Birre", [("Birra alla spina grande","","9,00"),("Birra alla spina media","","4,50"),("Birra alla spina piccola","","3,50"),
              ("Birra in bottiglia 66 cl","","4,50"),("Birra rossa in bottiglia 33 cl","","4,00"),
              ("Birra/Birra analcolica in bottiglia","","3,50")]),
   ("Vino della casa", [("Della casa 1/4 lt bianco o rosso","","3,50"),("Della casa 1/2 lt bianco o rosso","","5,00"),
              ("Della casa 1 lt bianco o rosso","","10,00"),("Spumante dolce o secco","","18,00")]),
   ("Rossi", [("Nero d'Avola","","18,00"),("Bonarda frizzante","","18,00"),("Pinot nero","","18,00"),
              ("Chianti","","18,00"),("Chianti (0,375)","","10,00")]),
   ("Bianchi", [("Pinot nero vinificato bianco","","18,00"),("Pinot grigio","","18,00"),("Müller Thurgau","","18,00"),
                ("Greco di Tufo","","18,00"),("Falanghina","","18,00"),("Chardonnay","","18,00"),("Vino bianco (0,375)","","10,00")]),
 ]),
]
