# Traduzioni inglesi del menù (usate da build_en.py).
# I nomi dei piatti restano in italiano; sotto compare la traduzione.

TABS = {
    "Antipasti": "Starters",
    "Primi": "Pasta & Risotto",
    "Secondi": "Main Courses",
    "Pizze": "Pizza",
    "Insalatone e contorni": "Salads & Sides",
    "Dolci e caffè": "Desserts & Coffee",
    "Bevande e vini": "Drinks & Wine",
}

GROUPS = {
    "Mare": "From the sea",
    "Terra": "From the land",
    "Classiche": "Classic",
    "Speciali": "Specials",
    "Bianche e focacce": "White pizzas & focacce",
    "Calzoni": "Calzoni",
    "Fantasia": "Fantasy",
    "Insalatone": "Main-course salads",
    "Cous cous": "Couscous",
    "Contorni": "Side dishes",
    "Formaggi": "Cheese",
    "Dolci": "Desserts",
    "Caffè": "Coffee",
    "Digestivo": "After-dinner drinks",
    "Bibite": "Soft drinks",
    "Birre": "Beer",
    "Vino della casa": "House wine",
    "Rossi": "Red wine",
    "Bianchi": "White wine",
}

# Nome italiano -> traduzione mostrata sotto il nome
DISHES = {
    # Antipasti – mare
    "Misto pesce crudo": "Mixed raw fish platter",
    "Antipasto Maremonti": "Maremonti seafood starter",
    "Alici marinate": "Marinated anchovies",
    "Antipasto di mare caldo": "Warm seafood starter",
    "Capesante gratinate 3 pz.": "Gratinated scallops (3 pcs)",
    "Carpaccio di spada al limone": "Swordfish carpaccio with lemon",
    "Cocktail di gamberi": "Prawn cocktail",
    "Crostini al salmone": "Salmon crostini",
    "Gamberetti/Piovra alla Catalana": "Catalan-style shrimp or octopus",
    "Impepata di cozze": "Peppered mussels",
    "Misto marinato": "Mixed marinated seafood",
    "Piovra con patate": "Octopus with potatoes",
    "Sautè di gamberi con carciofi freschi e trevisana": "Sautéed prawns with fresh artichokes and radicchio",
    "Tentacolo di polipo con rucola e pomodorini": "Octopus tentacle with rocket and cherry tomatoes",
    # Antipasti – terra
    "Affettato misto con grana": "Mixed cold cuts with Grana cheese",
    "Gnocco fritto con prosciutto crudo": "Fried dough with Parma-style ham",
    "Bresaola carciofi grana": "Bresaola with artichokes and Grana",
    "Bruschette": "Bruschetta",
    "Crostini di funghi porcini trifolati": "Crostini with sautéed porcini mushrooms",
    "Misto di bruschette": "Mixed bruschetta",
    "Crudo e bufala": "Cured ham and buffalo mozzarella",
    # Primi – mare
    "Spaghetti alle vongole e astice tagliato": "Spaghetti with clams and lobster",
    "Tagliatelle maremonti": "Maremonti tagliatelle",
    "Spaghetti sottocoperta": "Spaghetti “sottocoperta” (seafood)",
    "Spaghetti alle vongole veraci": "Spaghetti with clams",
    "Spaghetti alle vongole veraci e bottarga": "Spaghetti with clams and bottarga",
    "Linguine con gamberone e scampone": "Linguine with king prawn and langoustine",
    "Linguine all'astice": "Linguine with lobster",
    "Pappardelle gamberetti e zucchine": "Pappardelle with shrimp and courgettes",
    "Tagliatelle capesante e fiori di zucca": "Tagliatelle with scallops and courgette flowers",
    "Tagliatelle al salmone": "Tagliatelle with salmon",
    "Risotto con scampetti e fiori di zucca": "Risotto with langoustines and courgette flowers",
    "Risotto ai frutti di mare": "Seafood risotto",
    "Risotto gamberetti e rucola": "Risotto with shrimp and rocket",
    "Spaghetti al nero di seppia": "Spaghetti with cuttlefish ink",
    "Penne con scampi e zucchine": "Penne with langoustines and courgettes",
    # Primi – terra
    "Spaghetti alla carbonara": "Spaghetti carbonara",
    "Pappardelle ai funghi porcini": "Pappardelle with porcini mushrooms",
    "Penne della casa": "House penne",
    "Penne Sancho Panza": "Penne “Sancho Panza”",
    "Penne alla tirolese": "Tyrolean-style penne",
    "Risotto taleggio e pistacchio": "Risotto with Taleggio and pistachio",
    "Risotto trevisana e scamorza": "Risotto with radicchio and smoked scamorza",
    "Risotto ai funghi porcini": "Porcini mushroom risotto",
    "Risotto con spinaci e stracchino": "Risotto with spinach and stracchino cheese",
    "Gnocchi ai 4 formaggi": "Gnocchi with four cheeses",
    "Gnocchi alla sorrentina": "Gnocchi Sorrento-style (tomato and mozzarella)",
    "Gnocchi gorgonzola e pistacchio": "Gnocchi with gorgonzola and pistachio",
    "Gnocchi spinaci e zola": "Gnocchi with spinach and gorgonzola",
    "Tortellini speck e trevisana": "Tortellini with speck and radicchio",
    "Fusilli alla diavola con ragù e mozzarella": "Spicy fusilli with meat sauce and mozzarella",
    # Secondi – mare
    "Orata o branzino maremonti": "Sea bream or sea bass Maremonti-style",
    "Astice alla catalana": "Catalan-style lobster",
    "Branzino o orata al forno con patate e carciofi": "Baked sea bass or sea bream with potatoes and artichokes",
    "Branzino o orata al sale": "Sea bass or sea bream baked in salt",
    "Branzino o orata alla griglia": "Grilled sea bass or sea bream",
    "Filetto di branzino al cartoccio": "Sea bass fillet baked in parchment",
    "Filetto di branzino alla crema di limone o al vino bianco": "Sea bass fillet with lemon cream or white wine",
    "Filetto di branzino ai funghi porcini": "Sea bass fillet with porcini mushrooms",
    "Fritto misto": "Mixed fried seafood",
    "Misto di pesce alla griglia o gratinata": "Mixed grilled or gratinated fish",
    "Pesce spada alla griglia": "Grilled swordfish",
    "Pesce spada alla siciliana": "Sicilian-style swordfish",
    "Spiedini di gamberoni con verdure alla griglia": "King prawn skewers with grilled vegetables",
    "Tagliata di branzino con patate o rucola": "Sliced sea bass with potatoes or rocket",
    "Filetto di orata alla mediterranea": "Mediterranean-style sea bream fillet",
    "Tartar di salmone fresco": "Fresh salmon tartare",
    "Tagliata di salmone al pepe rosa": "Sliced salmon with pink pepper",
    "Zuppa di pesce": "Fish soup",
    # Secondi – terra
    "Costata all'antica": "Traditional rib steak",
    "Costata alla griglia": "Grilled rib steak",
    "Cotoletta alla milanese": "Milanese veal cutlet",
    "Entrecôte con patate": "Entrecôte with potatoes",
    "Filetto al cartoccio": "Beef fillet baked in parchment",
    "Filetto al pepe verde": "Beef fillet with green peppercorns",
    "Filetto alla griglia": "Grilled beef fillet",
    "Filetto con aceto balsamico": "Beef fillet with balsamic vinegar",
    "Filetto tartara": "Beef fillet tartare",
    "Filetto di manzo trifolato con funghi e riso bianco": "Beef fillet with sautéed mushrooms and white rice",
    "Filetto di manzo alla crema di tartufo": "Beef fillet with truffle cream",
    "Grigliata mista di carne": "Mixed grilled meats",
    "Tagliata di costata all'olio e rosmarino": "Sliced rib steak with oil and rosemary",
    "Tagliata di manzo con porcini": "Sliced beef with porcini mushrooms",
    "Tagliata di manzo con rucola e grana": "Sliced beef with rocket and Grana",
    "Tagliata di manzo con trevisana e scamorza": "Sliced beef with radicchio and smoked scamorza",
    # Insalatone
    "Maremonti": "Maremonti salad",
    "Zia Teresa": "“Aunt Teresa” salad",
    "Classica": "Classic salad",
    "La Fattoria": "“The Farm” salad",
    "Mar Rosso": "“Red Sea” salad",
    "Primavera": "“Spring” salad",
    # Cous cous
    "Cous cous di verdura": "Vegetable couscous",
    "Cous cous di pesce": "Seafood couscous",
    # Contorni
    "Insalata mista": "Mixed salad",
    "Patate fritte": "French fries",
    "Patate prezzemolate": "Potatoes with parsley",
    "Sautè di patate": "Sautéed potatoes",
    "Spinaci aglio e olio": "Spinach with garlic and oil",
    "Spinaci al burro": "Buttered spinach",
    "Trevisana saltata": "Sautéed radicchio",
    "Verdure alla griglia": "Grilled vegetables",
    "Verdure lesse": "Boiled vegetables",
    # Formaggi
    "Brie": "Brie",
    "Gorgonzola": "Gorgonzola",
    "Grana": "Grana",
    "Taleggio": "Taleggio",
    "Misto": "Mixed cheese platter",
    # Dolci
    "Dolci fatti in casa": "Homemade desserts",
    "Affogato al caffè": "Ice cream with espresso",
    "Affogato al liquore": "Ice cream with liqueur",
    "Ananas o frutta di stagione": "Pineapple or seasonal fruit",
    "Tartufo bianco o nero": "White or dark “tartufo” ice cream",
    "Torroncino semifreddo": "Nougat semifreddo",
    "Flute sorbetto al limoncello": "Limoncello sorbet",
    "Coppa gelato": "Ice cream cup",
    # Caffè
    "Caffè": "Espresso",
    "Corretto": "Espresso with a dash of liqueur",
    "Cappuccino": "Cappuccino",
    "Ginseng": "Ginseng coffee",
    "Decaffeinato": "Decaf",
    "Orzo": "Barley coffee",
    # Digestivo
    "Liquori": "Liqueurs",
    # Bibite
    "Acqua 3/4 lt": "Water 0.75 l",
    "Coca, Fanta, Sprite": "Coke, Fanta, Sprite",
    "Thè alla pesca o al limone": "Peach or lemon iced tea",
    # Birre
    "Birra alla spina grande": "Large draught beer",
    "Birra alla spina media": "Medium draught beer",
    "Birra alla spina piccola": "Small draught beer",
    "Birra in bottiglia 66 cl": "Bottled beer 66 cl",
    "Birra rossa in bottiglia 33 cl": "Bottled red ale 33 cl",
    "Birra/Birra analcolica in bottiglia": "Bottled beer / alcohol-free beer",
    # Vino
    "Della casa 1/4 lt bianco o rosso": "House wine ¼ l, white or red",
    "Della casa 1/2 lt bianco o rosso": "House wine ½ l, white or red",
    "Della casa 1 lt bianco o rosso": "House wine 1 l, white or red",
    "Spumante dolce o secco": "Sweet or dry sparkling wine",
    "Nero d'Avola": "Nero d'Avola",
    "Bonarda frizzante": "Sparkling Bonarda",
    "Pinot nero": "Pinot Noir",
    "Chianti": "Chianti",
    "Chianti (0,375)": "Chianti (0.375 l)",
    "Pinot nero vinificato bianco": "Pinot Noir vinified as white",
    "Pinot grigio": "Pinot Grigio",
    "Müller Thurgau": "Müller-Thurgau",
    "Greco di Tufo": "Greco di Tufo",
    "Falanghina": "Falanghina",
    "Chardonnay": "Chardonnay",
    "Vino bianco (0,375)": "White wine (0.375 l)",
}

# Descrizioni italiane dei piatti (non pizze) -> inglese
DESCRIPTIONS = {
    "porcini e ragù di manzo": "porcini mushrooms and beef ragù",
    "insalata verde, gamberetti, funghi porcini": "green salad, shrimp, porcini mushrooms",
    "insalata verde, straccetti di pollo, mais, pomodorini e salsa rosa": "green salad, chicken strips, sweetcorn, cherry tomatoes and cocktail sauce",
    "insalata verde, grana, rucola, gamberetti": "green salad, Grana, rocket, shrimp",
    "insalata verde, bocconcini di mozzarella, rucola, carote grattugiate": "green salad, mozzarella bites, rocket, grated carrots",
    "insalata verde, rucola, piovra, gamberetti, scaglie di grana": "green salad, rocket, octopus, shrimp, Grana shavings",
    "insalata verde, rossa, olive, pomodoro, tonno, uovo sodo": "green and red salad, olives, tomato, tuna, boiled egg",
}

# Ingredienti delle pizze, parola per parola
INGREDIENTS = {
    "pomodoro": "tomato", "pom.": "tomato", "mozzarella": "mozzarella", "mozz.": "mozzarella",
    "basilico": "basil", "olio": "oil", "aglio": "garlic", "origano": "oregano",
    "wurstel": "frankfurter", "patatine": "fries", "mozzarella di bufala": "buffalo mozzarella",
    "'nduja": "'nduja (spicy spreadable salami)", "cipolle": "onions", "cipolla": "onion",
    "cotto": "cooked ham", "prosciutto cotto": "cooked ham", "prosciutto": "ham",
    "prosciutto crudo": "cured ham", "crudo": "cured ham", "funghi": "mushrooms",
    "carciofi": "artichokes", "olive": "olives", "capperi": "capers", "acciughe": "anchovies",
    "rucola": "rocket", "salame piccante": "spicy salami",
    "misto frutti di mare (con mozzarella 10,50 €)": "mixed seafood (with mozzarella €10.50)",
    "misto verdure alla griglia": "mixed grilled vegetables", "scamorza": "smoked scamorza",
    "zola": "gorgonzola", "brie": "brie", "grana": "Grana", "speck": "speck", "tonno": "tuna",
    "gamberetti": "shrimp", "porcini": "porcini mushrooms", "radicchio": "radicchio",
    "stracchino": "stracchino cheese", "bresaola": "bresaola", "zucchine": "courgettes",
    "pancetta": "pancetta", "peperoncino": "chilli", "salsiccia": "sausage", "peperoni": "peppers",
    "scaglie di grana": "Grana shavings", "pomodoro fresco": "fresh tomato", "burrata": "burrata",
    "mortadella": "mortadella", "granella di pistacchi": "chopped pistachios",
    "friarielli": "friarielli (broccoli rabe)", "formaggi misti": "mixed cheeses",
    "ricotta": "ricotta", "metà calzone": "half calzone", "metà pizza": "half pizza",
    "zola peperoni": "gorgonzola, peppers",
}
